### ISSUE TITLE
Q: Is the plan to make SSA conversion the mainline?

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#121]
Hi @vnmakarov 

Noticed you are working on the ssa branch. Is the plan that SSA conversion will replace the current approach in MIR?
Are there any important benefits in doing so?
Finally any timeline when you plan to merge the ssa branch? I ask because I was wondering whether to update Ravi now with latest changes or wait until the ssa merge.

Thanks and Regards
Dibyendu

**Comment by vnmakarov** [comment]
Yes, I have plans to make SSA mainline.  Initially it was an experiment.  But now I see that the current SSA approach makes MIR-generator about 30% faster (for -O2) and the code simpler and a bit shorter.

 I use simpler approach to build and destroy SSA than usually industrial compilers use (semi-dominators -> dominators -> dominators frontiers, complicated out-of-SSA pass etc).

I am going to merge SSA branch into mainline during next couple weeks.

**Comment by dibyendumajumdar** [comment]
Sounds exciting! Looking forward to the merge

**Comment by rofl0r** [comment]
> the current SSA approach makes MIR-generator about 30% faster (for -O2) 

does it make the generated code faster or mir's execution time?

**Comment by vnmakarov** [comment]
> does it make the generated code faster or mir's execution time?

The generated code performance is the same on my small benchmarks.  SSA branch contains SSA reimplementation of sparse conditional constant propagation, dead code elimination and register renaming.  The branch also replaces CSE by GVN and removes LICM (for -O3) which improved generated code only by 1% on few my benchmarks but made MIR-generator too complicated.

Instead of LICM I am going to implement removing chain of extension instructions on SSA which is pretty common after inlining.
