### ISSUE TITLE
Infinite loop when initializing empty structs

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#183]
The following code makes `c2m` stuck in an infinite loop:

```C
typedef struct Empty {} Empty;
static Empty empty = {};
typedef struct Foo {
  int x;
  Empty nothing;
} Foo;
static Foo f(Empty nothing) {
  Foo m = {0};
  return m;
}
int main(int argc, char** argv) {
  f(empty);
  return 0;
}
```

Then when running with `c2m ./test.c -ei` the application never finishes, and the CPU is stuck at 100% usage.

Changing `static Empty empty = {};` to `static Empty empty;` the program runs fine.

I found this while testing some C generated code, I know it's not good to use empty structs, but this scenario happens with C code generated by an automated tool (it's not a user code).

This code runs fine on GCC/Clang/TCC.

**Comment by edubart** [comment]
Also another minor issue, the following triggers the warning `warning -- empty initializer list`, which is wrong in this case:
```C
Empty e = (Empty){};
```

**Comment by vnmakarov** [comment]
Thank you for reporting this.  The following commits fix the the major issue:

https://github.com/vnmakarov/mir/commit/6464267225474906bcc77a8157cc196e22daa213
and
https://github.com/vnmakarov/mir/commit/feceeb9ead5c224567c279b08b0dece6d2c4df45

Sorry, most of the 1st commit is formatting because I need to work on different machines and clang-format works differently on some machines and I can not fix it.

**Comment by edubart** [comment]
Thanks, the fix worked!
