### ISSUE TITLE
Is this support on android/ios?

### ISSUE THREAD

**Issue by LightSun** [vnmakarov/mir#203]

**Comment by vnmakarov** [comment]
Well, I am not planning to work on Android/IOS port.  But I welcome pull requests implementing this.

I don't think porting MIR to Android/IOS is a big job because code generation for aarch64 is already implemented. As I understand binary ABI for Android is just Linux aarch64 ABI and IOS ABI is close to M1 MacOSX ABI.  MIR was already ported to aarch64 Linux and M1 MacOSX.  So the most work is already done.

**Comment by LightSun** [comment]
@vnmakarov thanks
