### ISSUE TITLE
[C2M] Float constants from math.h give errors and warnings

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#23]
Doing some more tests with C2M I've found that the following is unable to compile:
```C
#include <stdio.h>
#include <math.h>
void main() {
  printf("%lf\n", NAN);
  printf("%lf\n", INFINITY);
  printf("%lf\n", HUGE_VAL);
  printf("%f\n", HUGE_VALF);
  printf("%Lf\n", HUGE_VALL);
}
```

When running the example with c2m the output is:
```
/usr/include/math.h:62:21: warning -- number 1e10000f is out of range
/usr/include/math.h:55:19: warning -- number 1e10000 is out of range
/usr/include/math.h:62:21: warning -- number 1e10000f is out of range
/usr/include/math.h:63:21: warning -- number 1e10000L is out of range
/usr/include/math.h:103:16: Division by zero
```

What was expected is no warnings or errors.

The culprits are those lines from GLIBC 2.30:
https://github.com/bminor/glibc/blob/glibc-2.30/math/math.h#L62
https://github.com/bminor/glibc/blob/glibc-2.30/math/math.h#L103

**Comment by vnmakarov** [comment]
Thank you for reporting this issue.  GLIBC uses GCC builtins for getting inifinity and NaN.  For non GCC conforming compilers, math.h uses big values and 0.0 / 0.0 for NAN.

I can not remove warnings because these warnings are useful in other cases but I can fix the error.  The patch will be  ready soon.

**Comment by vnmakarov** [comment]
Here is the patch
https://github.com/vnmakarov/mir/compare/84b277a..5f91154

**Comment by dibyendumajumdar** [comment]
Is there a way to get Nan, -Inf and Inf values in MIR.
I am using following in my C output but not sure if this works:

```
#define nan (0./0.)
#define inf (1./0.)
```

Basically in a JIT mode, it is better to not have to rely on any external headers; in Ravi, no headers are used, and I rely only upon MIR.

**Comment by vnmakarov** [comment]
> Is there a way to get Nan, -Inf and Inf values in MIR.
> I am using following in my C output but not sure if this works:
> 
> ```
> #define nan (0./0.)
> #define inf (1./0.)
> ```
> 

It might be target-dependent.  But for x86-64 1.0/0.0 is infinitity.  0.0/0.0 is actually -nan.  It is better to use function nanl for getting NAN or the following code
```
static unsigned long nan_long = 0x7fffffffffffffff;
#define nan (*(double *)&nan_long)
```
Another problem is that NAN and INFITITY is defined in math.h.  If I define builtin functions for such values and define macro `__GNUC__`, there would be no problem.  But defining `__GNUC__` would create much more other problems because most of GCC extensions are not implemented in `c2m` and a lot of programs check this to use these extensions.

> Basically in a JIT mode, it is better to not have to rely on any external headers; in Ravi, no headers are used, and I rely only upon MIR.

**Comment by dibyendumajumdar** [comment]
@vnmakarov Okay thank you. I suppose I can use just a macro - or would the static be optimized away?

I agree it is not a good idea to define __GNUC__ unless you want years of pain! :-)

Regards

**Comment by edubart** [comment]
As `<math.h>` can be included without issues since the patch and the warnings can be silenced with `-w`, I am closing this.
