### ISSUE TITLE
address of register

### ISSUE THREAD

**Issue by Itay2805** [vnmakarov/mir#235]
It would be very nice if there would be a MIR instruction to get the address of a register, which in a way will simply forcefully spill the register so a reference to it can be gotten. In theory this could be emulated by using alloca, but currently alloca has a pretty big overhead mainly because it will force MIR to generate memory accesses rather than just using normal registers, so having all variables be allocated with alloca is suboptimal and needing the frontend to analyze its own code would be pretty annoying from API standpoint...

**Comment by Itay2805** [comment]
I realized that this is not really needed especially once alias and point to analysis is implemented as it could be used to optimize anything to do with alloca, I will just use alloca for now

**Comment by vnmakarov** [comment]
Thank you for sharing your experience.

Yes, it can be annoying.  I had the same experience when I implemented C to MIR compiler.  Implementing this would make MIR a more high level language which might be a good and a bad thing.  I'll think about it.

By the way coming alias analysis can remove redundant loads and stores but still access to memory instead of reg can make generated code slower.
