### ISSUE TITLE
MIR_T_RBLK clarification

### ISSUE THREAD

**Issue by Itay2805** [vnmakarov/mir#263]
Reading in `MIR.md` I see that `MIR_T_RBLK` is a thing, but I am having a hard time understanding how to use it exactly:
- Is it basically `MIR_T_BLK` but passed by ref, or is it something more than that? 
- Can you have multiple RBLKs, or should you only have one 
- Does it matter which argument is the RBLK, or can it be any argument
- Is there a real difference between passing a pointer and using an RBLK?

**Comment by vnmakarov** [comment]
> * Is it basically `MIR_T_BLK` but passed by ref, or is it something more than that?
> 

It is more than that.  MIR_T_RBLK is added to implement C ABI compatibility on different targets.  E.g. small records on x86-64 can be returned through hard regs.  On other targets the same MIR_T_RBLK can be implemented by reserving stack space in caller func and passing it to the callee.  This type hides the particular target ABI still implementing C ABI on the target

> * Can you have multiple RBLKs, or should you only have one
> 

I'd say more one RBLKs is undefined behaviour.  On some targets it can work, on some it will result in the problems.

> * Does it matter which argument is the RBLK, or can it be any argument
>

The same as in the above.  To avoid problems, use RBLK as the 1st arg.
  
> * Is there a real difference between passing a pointer and using an RBLK?

Yes.  I explained this in the first answer.

There are a lot of undefined behaviour mentioned in MIR description because MIR support different target ABIs.
For example, on some targets multiple return values are supported on some targets only one result is possible.  There are also constraints (defined y ABI) on number of return values when multiple return values are possible.
I'd like to remove these constraints (it basically means extension of existing target ABIs) but it is a big job and it is not high priority jobs for me now.

**Comment by Itay2805** [comment]
that is quite interesting, do you think for better ABI compat RBLK should always be used for returning values? assuming that it does thing like using regs when possible it seems to be quite a positive thing. so the ABI can handle different sizes or whatever by itself? 

Also I assume the answer is undefined behavior / ABI defined, but can RBLK and return values be used at the same time?

**Comment by vnmakarov** [comment]
> that is quite interesting, do you think for better ABI compat RBLK should always be used for returning values? assuming that it does thing like using regs when possible it seems to be quite a positive thing. so the ABI can handle different sizes or whatever by itself?
> 

If you call a C function which returns an aggregate type, you should use RBLK for ABI compatibility.

The problem with target ABIs they work on C type level (that means structures/arrays too).  MIR has no aggregate types.  I could add aggregate types to MIR (as it is done in LLVM IR) but it would complicate the IR considerably.  So I just introduced BLK and RBLK types which describe all possible call ABI cases for targets supported by MIR.  For example, different BLK types will result in different ways of passing args on some targets and the same passing way on other targets (as for LLVM IR, it will have small structure descriptions for args on one target and absent structure on another target).

Although I wanted to make MIR portable, it is impossible to achieve (as for LLVM IR) if we want compatibility for ABIs and aggregate type layout ABI.  Stiil if you use only primitive types, MIR is portable.

In general MIR portability (as LLVM IR) is very complicated topic.  The best way to avoid the complexity is to generate MIR and use it only the same target.


> Also I assume the answer is undefined behavior / ABI defined, but can RBLK and return values be used at the same time?

Yes, I guess for x86-64, you can do this.  But c2m will never generate such MIR code.
