### ISSUE TITLE
Re-using the C parser

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#75]
Hi, 
I was wondering if one might be able to reuse the C parser. Since I use the C to MIR translator in Ravi, I would like to also implement an LLVM backend for the MIR C parser, so that I can easily compare the performance of LLVM vs MIR. 
Is there a reason why this would not be possible?
Thanks and Regards
Dibyendu

**Comment by vnmakarov** [comment]
There are no obstacles to do this according to my license.  It is only difficult to me understand what are you going to achieve.
* If you want to compare speed of code generated by c2mir to clang/llvm, you can do this now.  I use `make c2mir-bench` to evaluate a generated code performance for a new port.  You can do the same for bigger benchmarks.  Of course, if they are written on standard C11 (many most interesting program/benchmarks use a lot of C extensions).
* If you want to compare C parsers speed (c2mir and clang), I can say that **raw** speed of clang should be faster because c2mir parser was not designed for the speed.  It uses backtracking and pass separation for simplicity.  C2MIR parser should have much faster startup than Clang or GCC parser.  So it should be faster on small C programs (saying < 50 lines).
* If you want to use C2MIR parser as replacement for clang, it is very difficult work.  Clang and GCC supports so many extensions and builtins.  Implementing it would mean the same amount of work as writing the current c2mir itself.  Also nobody is interesting in C only parsers.  People are interesting in C/C++ parsers and that is in order magnitude bigger work.

Also implementing MIR C/LLVM could be done from MIR C AST or from MIR itself.  I think MIR->LLVM IR is more doable work.  But I can see right now where it could be used.  Therefore I don't put this on my possible future diagram https://github.com/vnmakarov/mir#the-possible-future-state-of-mir-project

For example, MIR->Java byte code has sense because it permits to run MIR code on JAVA VM.  Java byte code -> MIR could be used for alternative implementation of languages targeting JVM.  Goals MIR->LLVM IR could be achieved by MIR->C.  The speed of MIR to C is not issue as a C parser in optimized compilers consumes a tiny portion of CPU time.

**Comment by dibyendumajumdar** [comment]
Hi,
I was thinking of starting at the AST level and translating to LLVM IR. Just as C2MIR translates to MIR. I already have LLVM support in Ravi ... the alternative is to link Libclang and do it that way but Libclang is a huge library. But maybe using Libclang is better as then I would be able to see the real world difference between Clang and MIR. 

The goal is to see the runtime performance of JITed code - comparing LLVM with MIR - both starting with C code

**Comment by vnmakarov** [comment]
> The goal is to see the runtime performance of JITed code - comparing LLVM with MIR - both starting with C code.
> 

I see.  Yes, it is interesting.  Actually the whole project was started because to solve some problems with current Ruby JIT which uses GCC/LLVM as a JIT compiler and C as an interface language.

Definitely the code generated by MIR will be slower (may be even in 2 times) but because of faster MIR compilation I can use more aggressively inlining and speculation/deoptimization technique (inlining and speculation have a very good potential to generate a good JITted code for Ruby). The future will tell how my ideas will work when MIR is used for Ruby JIT.  I am looking forward to start MIR Ruby JIT work but MIR is not ready for this yet.  I still need to implement speculation support in MIR and C2MIR, stabilize MIR project, and make a MIR release for this. 

> I should add that I need to see this in context - i.e. with Ravi, rather than standalone C programs, because optimizing Ravi code is more challenging

**Comment by dibyendumajumdar** [comment]
>  The future will tell how my ideas will work when MIR is used for Ruby JIT. I am looking forward to start MIR Ruby JIT work but MIR is not ready for this yet. I still need to implement speculation support in MIR and C2MIR, stabilize MIR project, and make a MIR release for this.
> 

My experience is that MIR does well when type information is available and is with 2x of LLVM performance. But when type info is lacking, I don't see much difference compared to interpreted code, even worse sometimes.
