### ISSUE TITLE
Question about MIR inlining

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#80]
Right now I have some C functions that are compiled outside of MIR. I was wondering if I should instead compile them into a MIR module and link this, so that MIR can inline.

How does the in-lining work? Will it be triggered automatically? 

Thanks and Regards
Dibyendu

**Comment by vnmakarov** [comment]
The inlining happens when you have reference to function in MIR_CALL and MIR_INLINE.  If it is some other value which is function address, inlining does not happen.  Of course, the referenced function should be in a loaded module.  Otherwise, it will be not found.

Even if you have a reference to function in MIR_CALL or MIR_INLINE insns, inlining happens only if inlining does not increase the current function code size by 50%.  The inlined functions should be not more 50 MIR insns for MIR_CALL and 200 MIR insns for MIR_INLINE.  That is the current heuristics. They can change in the future.  You can change the inlining criteria by redefining macros
`MIR_MAX_INSNS_FOR_INLINE`, `MIR_MAX_INSNS_FOR_CALL_INLINE`, and `MIR_MAX_FUNC_INLINE_GROWTH`.

Inlining happens at link time right after the simplification.

**Comment by dibyendumajumdar** [comment]
> The inlining happens when you have reference to function in MIR_CALL and MIR_INLINE. If it is some other value which is function address, inlining does not happen. Of course, the referenced function should be in a loaded module. Otherwise, it will be not found.
> 

Presumably this will work if all modules were compiled using C2MIR?

> Even if you have a reference to function in MIR_CALL or MIR_INLINE insns, inlining happens only if inlining does not increase the current function code size by 50%. The inlined functions should be not more 50 MIR insns for MIR_CALL and 200 MIR insns for MIR_INLINE. That is the current heuristics. They can change in the future. You can change the inlining criteria by redefining macros
> `MIR_MAX_INSNS_FOR_INLINE`, `MIR_MAX_INSNS_FOR_CALL_INLINE`, and `MIR_MAX_FUNC_INLINE_GROWTH`.
> 
> Inlining happens at link time right after the simplification.

Okay thanks

**Comment by vnmakarov** [comment]
> Presumably this will work if all modules were compiled using C2MIR?

It does not matter who produces MIR module.  As soon as it is loaded in the same context, its functions are considered for inlining.
