### ISSUE TITLE
Please describe any compilattion flags needed to build MIR on different platforms

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#89]
Hi, 
I am using a CMake build to make MIR - and I  kind of reverse engineered what was needed from MIR Makefile, but this was a while back. I think it would be useful if there was some description of the build flags needed to compile MIR on various platforms.

Thanks and Regards
Dibyendu

**Comment by vnmakarov** [comment]
Currently, MIR support 4 targets (x86_64, aarch64, ppc64be/le, s390x).  There are no target specific flags.  The target specific code is chosen through target specific macros of host compiler (GCC/Clang).

The project code uses C11 features.  Therefore it needs `-std=c11`.  C2MIR code assumes that char is signed.  Therefore it needs `-fsigned-char`.
 
There are additional options `-fno-tree-sra` and `-fno-ipa-cp-clone` for GCC because some GCC versions have bugs in the corresponding optimizations affecting MIR code.

Plus MacOSX needs the additional include directories `$(shell xcrun --show-sdk-path)/usr/include`.

**Comment by dibyendumajumdar** [comment]
Okay thank you. 
How about flags like MIR_NO_IO, MIR_NO_SCAN, etc.?

Regards

**Comment by vnmakarov** [comment]
> How about flags like MIR_NO_IO, MIR_NO_SCAN, etc.?

I would say they are internal macros now.  They might become public for some specific applications (very constrained by code size).

**Comment by dibyendumajumdar** [comment]
Okay thank you
