### ISSUE TITLE
Save/restore XMM registers

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#93]
I've hit the xmm regs assert in target_make_prolog_epilog today:
assert (i <= R15_HARD_REG); /* xmm regs are always callee-clobbered */

On Windows only the first 6 XMM regs are callee-clobbered. The others have to be saved/restored which would require movdqa or movdqu instruction support?

**Comment by vnmakarov** [comment]
Yes. I see the problem. MIR_DMOV (movsd) saves only 64-bit of 128 bit required..  I think you should use MIR_DMOV now.  At least it makes MIR code called by another MIR code working (because MIR code never use high part of xmm registers).  Unfortunately, high part of xmm reg is zeroed during load from  memory. So we really need to use movdqa to save xmm regs according to ABI.

   I need to think how better to solve the problem.  I hope to find and implement a solution in 1-2 weeks.

**Comment by logzero** [comment]
#97
