### ISSUE TITLE
Should thread management be MIR concern

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#96]
Hi 
I noticed that you are working on adding multi-threaded codegen to MIR? I feel that ideally MIR should be thread safe and allow client code to manage threads rather than having multi-threading inbuilt, as how threads are managed should really be client concern. I am a bit worried that MIR will start causing unforeseen CPU impact.
Regards

**Comment by vnmakarov** [comment]
Thank you for expressing your concerns.  I'd like to play them down.

* First of all, what I am trying might be never be in the mainline.  I am just experimenting.  If the results will be satisfactory (scalability), I probably add this code
* The user will have full control to use threads in `MIR_set_gen_interface` or create own threads and use them to work with the generator in parallel.
* Also all parallelism can be switched off completely during compiling MIR sources

So user will have  full control to switch parallelism off dynamically or statically (during building MIR object files).  My goal is also to add as less code as possible.

Unfortunately, making all MIR interface functions thread-safe has no sense with the performance point of view.  The granularity of some very frequently called functions (dealing with insns and regs) are so small that making them thread-safe will not improve performance (more probably even hurt the performance) when several threads are used as the threads (and CPUs) will spent most time in spinlocks trying to get a mutex lock.

What I am trying to do is only to make generator work in parallel (because most time in JIT data flow will be spent in it) on **separate functions** with minimum locks.  The big part of this work is to localize data used/modified by the generator during its work on one function.

By the way, I am going to parallelize C2MIR too but it will be done on module (source file) basis.  Again, the user will have full control to switch it off dynamically (or use specific number threads) or statically (during building `c2m`).

**Comment by dibyendumajumdar** [comment]
Hi @vnmakarov 

Thank you for detailed reply as always.

>     * The user will have full control to use threads in `MIR_set_gen_interface` or create own threads and use them to work with the generator in parallel.
> 
>     * Also all parallelism can be switched off completely during compiling MIR sources
>
> 
> So user will have full control to switch parallelism off dynamically or statically (during building MIR object files). My goal is also to add as less code as possible.
>

Okay thank you. I would certainly prefer avoiding the increase in MIR code / complexity. 

> Unfortunately, making all MIR interface functions thread-safe has no sense with the performance point of view. The granularity of some very frequently called functions (dealing with insns and regs) are so small that making them thread-safe will not improve performance (more probably even hurt the performance) when several threads are used as the threads (and CPUs) will spent most time in spinlocks trying to get a mutex lock.

Agreed. I wasn't thinking that all of MIR should be thread safe. In a way by avoiding global state MIR is already thread-safe because different MIR contexts in different threads will not conflict. 
 
> 
> What I am trying to do is only to make generator work in parallel (because most time in JIT data flow will be spent in it) on **separate functions** with minimum locks. The big part of this work is to localize data used/modified by the generator during its work on one function.
> 
> By the way, I am going to parallelize C2MIR too but it will be done on module (source file) basis. Again, the user will have full control to switch it off dynamically (or use specific number threads) or statically (during building `c2m`).

Sure. I am not fully familiar with how things work inside MIR, but my starting assumption is that MIR is already thread-safe as all state is local to a context. So an alternative scenario might be:

a) User can setup multiple compilation contexts and compile in multiple threads.
b) The linking and final code cache can be a single separate context - and would be the only part that needs to be thread-safe.

Anyway if the plan is to allow client to completely remove the threading code via #if condition then  at least it is no risk for someone who doesn't want it. I would certainly prefer to completely disable / remove the code as I don't see a use case for it.

Regards

**Comment by vnmakarov** [comment]
> Sure. I am not fully familiar with how things work inside MIR, but my starting assumption is that MIR is already thread-safe as all state is local to a context. So an alternative scenario might be:
> 
> a) User can setup multiple compilation contexts and compile in multiple threads.
> b) The linking and final code cache can be a single separate context - and would be the only part that needs to be thread-safe.

Your are right MIR is already thread-safe if only one thread uses one context.  But different contexts make MIR-code completely disconnected (still somebody can make them connected through `MIR_load_external` but it could be a complicated solution, a non-intuitive trick basically).

I thought about sub-contexts (or even tree contexts as in LIBGCCJIT) but the design looked very complicated and non-intuitive.  I think about implementing thread-safe context merging.  It will be needed for parallel compiling C source files in c2mir driver where for which C source file a MIR module in own context is created and then all modules are put in one context and then machine code for functions from each modules could be generated in parallel.

But how to make parallel generation of functions from one module (it is minimal unit for context in the current design) w/o approach I am currently implementing.  An alternative solution I can see is we could split module with many functions into several modules with smaller number functions in different contexts to generate code for them in parallel.  I think it is more complicated solution: how to split, extending MIR semantics to refer module items which are not external, etc.

So currently the current solution I am implementing is the simplest one between other I considers:
We have several generators (their number is defined in `MIR_gen_init`) which can generate code from a separate thread.  We can use a particular generator in call of `MIR_gen`.  

`MIR_set_gen_interface` and `MIR_set_lazy_gen_interface` are layers over `MIR_gen`.  There will be `MIR_set_parallel_gen_interface` and `MIR_set_parallel_lazy_gen_interface` where actually threads are created for parallel generations by the generators.  A user can ignore these functions completely and create own threads and call a particular generator (by `MIR_gen`) from the threads.

We don't need concurrency/parallelism anywhere besides generator (as generator is the most CPU-intensive part).  So introducing several generators (in someway the generator number defines a subcontext for the generator) is an adequate solution when each generator can be called for different functions from different threads.
